[build-system]
requires = ["flit_core"]
build-backend = "flit_core.buildapi"

[project]
name = "hw-tests"
description = "Run hardware tests like there is no tomorrow!"
readme = "README.md"
authors = [
    {name = "Linux Factory", email="linux@analog.com"}
]
license = {text = "BSD-2-Clause"}
classifiers = [
    "Development Status :: 1 - Planning",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: BSD License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: Implementation :: CPython",
]
dependencies = [
    "pytest",
    "labgrid @ git+https://github.com/analogdevicesinc/labgrid.git@adi-next",
    "requests",
]
requires-python = ">=3.11"
dynamic = ["version"]

[project.optional-dependencies]

test = [
    "ruff",
]

[tool.setuptools.packages.find]
where = [""]
include = ["hw_tests*"]
namespaces = true

[tool.pytest.ini_options]
minversion = "9.0"
addopts = [
    "-ra",
    "--strict-config",
    "--strict-markers",
    "--import-mode=importlib"
]
log_format = "%(levelname)-7.7s %(name)s: %(message)s"
log_cli_format = "%(levelname)-7.7s %(name)s: %(message)s"

python_files = ["test.py", "test_*.py"]


markers = [
    "smoke: validates the environment and the test framework",
    "uboot: U-Boot related hardware tests",
    "linux: Linux boot related hardware tests",
    "bootstrap: bootstrap Linux and install U-Boot to SPI flash",
]
