name: Run Test

inputs:
  set:
    # { "name": "adsp/bootstrap", "target": "..." }
    description: "Test set"
    default: ""
  github-token:
    description: "GitHub Token"
    default: ${{ github.token }}

runs:
  using: "composite"
  steps:
    - name: Install test dependencies
      shell: bash
      env:
        set: ${{ inputs.set }}
      run: |
        # Install test dependencies
        venv=$(mktemp -dt hw-test.XXX)
        echo "venv=$venv" >> "$GITHUB_ENV"

        python3 -m venv $venv
        source "$venv/bin/activate"
        pip3 install -e '.[test]'
        name=$(echo "$set" | jq -r '.name')
        [ -f "tests/${name}/requirements.txt" ] && pip install -r "tests/${name}/requirements.txt" || :

    - name: Run test
      shell: bash
      env:
        set: ${{ inputs.set }}
        GITHUB_TOKEN: ${{ inputs.github-token }}
      run: |
        # Run test
        source "$venv/bin/activate"
        [[ "${{ runner.debug }}" == "1" ]] && v="-v"
        pytest $v

    - name: Clean-up
      shell: bash
      if: always()
      run: |
        # Clean-up
        rm -rf "$venv"
