name: Run Test

inputs:
  set:
    # { "name": "adsp/bootstrap", "target": "..." }
    description: "Test set"
    default: ""
  github-token:
    description: "GitHub Token"
    default: ${{ github.token }}

runs:
  using: "composite"
  steps:
    - name: Run test
      shell: bash
      env:
        set: ${{ inputs.set }}
        GITHUB_TOKEN: ${{ inputs.github-token }}
      run: |
        # Run test
        python3 -m venv venv
        source ./venv/bin/activate
        python3 -m ensurepip
        pip3 install -e '.[test]'
        name=$(echo "$set" | jq -r '.name')
        [ -f "tests/${name}/requirements.txt" ] && pip install -r "tests/${name}/requirements.txt" || :
        [[ "${{ runner.debug }}" == "1" ]] && v="-v"
        pytest $v
