FROM fedora:44

ENV version=v1

ARG bashrc=https://raw.githubusercontent.com/analogdevicesinc/doctools/refs/heads/ci/bashrc
ARG entrypoint_sh=https://raw.githubusercontent.com/analogdevicesinc/doctools/refs/heads/ci/entrypoint.sh
ARG git_defaults_sh=https://raw.githubusercontent.com/analogdevicesinc/doctools/refs/heads/ci/git-defaults.sh
ARG gh_actions_runner_sh=https://raw.githubusercontent.com/analogdevicesinc/doctools/refs/heads/ci/gh-actions-runner.sh

RUN dnf -y upgrade
RUN dnf -y install \
    tar unzip gzip curl jq libicu coreutils \
    sudo shadow-utils

RUN useradd -m runner
WORKDIR /home/runner

ADD ${gh_actions_runner_sh} .
RUN bash ./gh-actions-runner.sh ; rm ./gh-actions-runner.sh

RUN dnf -y install \
    python3 python3-pip \
    opkssh \
    git openssh-clients rsync curl wget \
    tar gzip unzip \
    iproute

RUN mkdir -p /usr/local/bin
WORKDIR /usr/local/bin
ADD ${entrypoint_sh} .
RUN chmod +rx ./entrypoint.sh

ADD ${git_defaults_sh} .
RUN bash ./git-defaults.sh ; rm ./git-defaults.sh

USER runner
WORKDIR /home/runner
RUN curl -o .bashrc -L ${bashrc} ; \
    chmod +x .bashrc

ENTRYPOINT ["/bin/bash"]
