name: Package tests

on:
  push:
    branches:
      - main
      - staging/*
  pull_request:

jobs:
  package-tests:
    runs-on: ${{ vars.RUNNER != '' && fromJSON(vars.RUNNER) || 'ubuntu-latest' }}
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v6
    - name: Install pip packages
      run: |
        python3 -m venv venv
        source ./venv/bin/activate
        python3 -m ensurepip
        pip3 install -e '.[test]' --upgrade
        pip3 install ruff --upgrade

    - name: Run test
      shell: bash
      run: |
        source ./venv/bin/activate
        [[ "${{ runner.debug }}" == "1" ]] && v="-v"
        pytest hw_tests $v

    - name: Ruff lint
      run: |
        source ./venv/bin/activate
        ruff check --output-format=github .
