name: Run Tests
run-name: Run Tests for ${{ inputs.workflow_run_url }}

on:
  workflow_dispatch:
    inputs:
      workflow_run_url:
        description: "The api url of the workflow_run"
        required: true
        type: string

jobs:
  collect:
    runs-on: ${{ vars.RUNNER != '' && fromJSON(vars.RUNNER) || 'ubuntu-slim' }}
    permissions:
      contents: read
    outputs:
      tests: ${{ steps.collect.outputs.tests }}
      names: ${{ steps.collect.outputs.names }}

    steps:
    - uses: analogdevicesinc/doctools/workflow-run-to-context@action
      id: context
      with:
        url: ${{ inputs.workflow_run_url }}

    - uses: actions/checkout@v6

    - name: Collect tests to run
      id: collect
      env:
        context: ${{ toJson(steps.context.outputs) }}
      run: python3 -m hw_tests.collect

  run-tests:
    needs: collect
    if: needs.collect.outputs.names != '[]'
    permissions:
      id-token: write
      contents: read
    strategy:
      fail-fast: false
      matrix:
        name: ${{ fromJson(needs.collect.outputs.names) }}
    uses: ./.github/workflows/run-test.yml
    with:
      name: ${{ matrix.name }}
      set: ${{ needs.collect.outputs.tests }}
