name: Run Test
run-name: Run Test for ${{ fromJson(inputs.set).name }}

on:
  workflow_dispatch:
    inputs:
      set:
        # { "name": "demo/linux-iio-dac", "repository": { "linux": { "ref": "010c..." } } }
        description: "Test set"
        required: true
        default: '{ "name": "demo/linux-iio-dac" }'
        type: string
  workflow_call:
    inputs:
      set:
        required: true
        type: string


jobs:
  run-test:
    runs-on: ${{ vars.RUNNER != '' && fromJSON(vars.RUNNER) || 'ubuntu-slim' }}
    env:
      LG_COORDINATOR: ${{ secrets.LG_COORDINATOR }}
    permissions:
      id-token: write
      contents: read
      actions: read

    steps:
    - uses: actions/checkout@v6
      with:
        repository: 'analogdevicesinc/hw-test'

    - uses: ./run-test
      with:
        set: ${{ inputs.set }}
