name: Run Test
run-name: Run Test for ${{ inputs.name }}

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Test to run"
        required: true
        type: string
      set:
        # { "name": "demo/linux-iio-dac", "with": { "linux": { "ref": "010c..." } } }
        description: "Test context"
        required: false
        type: string
  workflow_call:
    inputs:
      name:
        required: true
        type: string
      set:
        required: false
        type: string


jobs:
  run-test:
    runs-on: ${{ vars.RUNNER != '' && fromJSON(vars.RUNNER) || 'ubuntu-slim' }}
    permissions:
      id-token: write
      contents: read
    steps:
    - uses: actions/checkout@v6

    - name: Run test
      env:
        name: ${{ inputs.name }}
        set: ${{ inputs.set }}
      run: |
        python3 -m venv venv
        source ./venv/bin/activate
        python3 -m ensurepip
        pip3 install -e .
        python3 -m hw_tests.run
